### check AWS S3 policy ###
# Checks for all things related to S3 buckets
---
- name: Check S3 Policy Compliance
  hosts: localhost
  vars:
    algorithm: AES256
  policies:
    - name: Check for mandatory use of encryption 2
      target: task
      condition:
        any:
        - input["amazon.aws.s3_bucket"].encryption is not defined
        - input["amazon.aws.s3_bucket"].encryption != algorithm
      actions:
        - deny:
            msg: AWS S3 bucket encryption does not meet standards
      tags:
        - compliance
