### No shell or command usage policy ###
# This policybook checks if someone is using the shell or command or other similar 'script' modules
# This will check both FQCN and non-FQCN for module checks 
---
- name: Check for disallowed modules usage
  hosts: localhost 
  vars:
    disallowed_modules:
      - ansible.builtin.shell
      - ansible.builtin.command
      - ansible.builtin.raw
      - ansible.builtin.script
      - ansible.windows.win_shell
      - ansible.windows.win_command
  policies:
    - name: Check for disallowed module usage
      target: task
      condition: input._agk.task.module_info.fqcn in disallowed_modules or input._agk.task.module in disallowed_modules
      actions:
        - deny:
            msg: You are not allowed to run scripts or shell commands in automation jobs
      tags:
        - compliance
