### checks for Cisco IOS configuration compliance
# This policybook checks for IOS misconfigurations
---
- name: Check Cisco IOS configuration settings
  hosts: localhost 
  vars:
    banned_configurations:
      telnet:
        - line vty 0
        - no login
  policies:
    - name: Check on IOS configuration
      target: task
      condition: 
        any:
        - input["cisco.ios.ios_config"].lines in banned_configurations.telnet
      actions:
        - warn:
            msg: "WARNING: Cisco IOS settings violation"
      tags:
        - security
