---
- name: Enforce use of kubeconfig when using kubernetes modules
  hosts: localhost
  policies:
    - name: check module arguments to only use kubeconfig
      target: task
      condition: input["kubernetes.core.k8s"].kubeconfig is not defined
      actions:
        - deny:
            msg: use kubeconfig
