### check EC2 usage policy ###
# This policybook prohibit EC2 instances without a VPC.
# If a task using amazon.aws.ec2_instance module does not have vpc_subnet_id option, the violation will be detected.
---
- name: Prohibit EC2 instances without a VPC
  hosts: localhost 
  policies:
    - name: Prohibit EC2 instances without a VPC
      target: task
      condition: input["amazon.aws.ec2_instance"] lacks key vpc_subnet_id
      actions:
        - deny:
            msg: creating EC2 instances without a VPC is prohibited. specify vpc_subnet_id.
      tags:
        - compliance