### check instance access policy ###
# This policybook prohibit publicly accessible RDS instances.
# If the option publicly_accessible is set to true in a task using amazon.aws.rds_instance, a violation will be detected.
---
- name: Prohibit publicly accessible RDS instances
  hosts: localhost 
  policies:
    - name: Prohibit publicly accessible RDS instances
      target: task
      condition: 
        any:
        - input["amazon.aws.rds_instance"].publicly_accessible == true
      actions:
        - deny:
            msg: it is not allowed to create publicly accessible RDS instances
      tags:
        - compliance